---
- name: checking for agent install
  win_service:
    name: 'Snare'
  register: agent

- debug:
    msg: "snare agent not found (installing)"
  when: not agent.exists

- debug:
    msg: "snare agent found (skipping install)"
  when: agent.exists

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    state: directory
  when: not agent.exists

- name: create {{ windows_snare_agent_path }} directory
  win_file:
    path: '{{ windows_snare_agent_path }}'
    state: directory
  when: not agent.exists

- name: copy snare.inf to {{ windows_snare_agent_path }} directory
  win_get_url:
    url: '{{ snare_agent_config_url }}'
    dest: '{{ windows_snare_agent_path }}\snare.inf'
    timeout: 600
  when: not agent.exists

- name: install windows snare agent
  win_package:
    path: '{{ windows_snare_agent_url }}'
    chdir: '{{ windows_snare_agent_path }}'
    product_id: '{{ windows_snare_product_id }}'
    state: present
    arguments:
      - /reinstall
      - /verysilent
      - /suppressmsgboxes
      - /loadinf=snare.inf
    log_path: '{{ windows_agent_log }}\snare_log.txt'
  when: not agent.exists

- name: verify snare started
  win_service:
    name: Snare
    enabled: yes
    state: started
    start_mode: auto
